### ISSUE TITLE
Concat privkey and fullchain fails on renewal

### ISSUE THREAD

**Issue by Dalstroem** [linuxserver/docker-letsencrypt#224]
When my certificate has been renewed, the file "priv-fullchain-bundle.pem" is always empty and an error is thrown in the log. I'm running **Docker 18.06.1-ce** on **unRAID 6.6.3**.

```
<------------------------------------------------->
cronjob running on Mon Oct 22 02:08:00 CEST 2018
Running certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/mydomain.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator dns-cloudflare, Installer None
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for mydomain.com
dns-01 challenge for mydomain.com
Unsafe permissions on credentials configuration file: /config/dns-conf/cloudflare.ini
Waiting 10 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/mydomain.com/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/mydomain.com/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Running post-hook command: if ps aux | grep [n]ginx: > /dev/null; then s6-svc -h /var/run/s6/services/nginx; fi;     cd /config/keys/letsencrypt &&     openssl pkcs12 -export -out privkey.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem -passout pass: &&     cat {privkey,fullchain}.pem > priv-fullchain-bundle.pem
Hook command "if ps aux | grep [n]ginx: > /dev/null; then s6-svc -h /var/run/s6/services/nginx; fi;     cd /config/keys/letsencrypt &&     openssl pkcs12 -export -out privkey.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem -passout pass: &&     cat {privkey,fullchain}.pem > priv-fullchain-bundle.pem" returned error code 1
Error output from if:
cat: {privkey,fullchain}.pem: No such file or directory
<------------------------------------------------->
```

As far as I can tell this bundle file was added in PR #131. As a workaround I have been manual fixing it by running this on my unRAID server:

```
cat privkey.pem fullchain.pem > priv-fullchain-bundle.pem
```

**Comment by aptalca** [comment]
I have seen that issue on some users' logs. It's one of those intermittent things. Some daisy chained commands in docker fail because it tries to run them too soon, and if it looks for the files before the prior process releases them, it will give that error. 

So I already put a `sleep 1` in one of the dev branches and it will be merged soon: https://github.com/linuxserver/docker-letsencrypt/blob/duckdns/root/app/le-renew.sh#L23

Hopefully it will take care of that, but it's not an easy thing to test as I can't even reproduce it on my system here (I can't think of another reason for it to fail so this has got to fix it)

**Comment by Dalstroem** [comment]
Yeah hopefully `sleep 1` would give it enough time to create the `privkey.pem` and `fullchain.pem` files. I have had this issue for the last 3 renewals (9 months).

Will update again when the patch has been released and my certificate renewed.

Keep up the good work!

**Comment by aptalca** [comment]
hopefully fixed in #232

**Comment by MisterWil** [comment]
My cert just renewed and even with the `sleep 1` I had the same issue @Dalstroem mentioned above.

```
<------------------------------------------------->
cronjob running on Tue Jan 1 02:08:00 PST 2019
Running certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Non-interactive renewal: random delay of 216 seconds

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/domain.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator dns-cloudflare, Installer None
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for domain.com
dns-01 challenge for domain.com
Unsafe permissions on credentials configuration file: /config/dns-conf/cloudflare.ini
Waiting 10 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/domain.com/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/domain.com/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Running post-hook command: if ps aux | grep [n]ginx: > /dev/null; then s6-svc -h /var/run/s6/services/nginx; fi;     cd /config/keys/letsencrypt &&     openssl pkcs12 -export -out privkey.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem -passout pass: &&     sleep 1 &&     cat {privkey,fullchain}.pem > priv-fullchain-bundle.pem
Hook command "if ps aux | grep [n]ginx: > /dev/null; then s6-svc -h /var/run/s6/services/nginx; fi;     cd /config/keys/letsencrypt &&     openssl pkcs12 -export -out privkey.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem -passout pass: &&     sleep 1 &&     cat {privkey,fullchain}.pem > priv-fullchain-bundle.pem" returned error code 1
Error output from if:
cat: {privkey,fullchain}.pem: No such file or directory
```

**Comment by aptalca** [comment]
Already fixed in #250

**Comment by MisterWil** [comment]
OK cool wasn't sure if this was the same issue the `sleep 1` was supposed to fix or not and couldn't find an issue related to this. Glad it's already fixed. Thanks!

**Comment by Dalstroem** [comment]
My certificate was renewed on the December 21th, but "priv-fullchain-bundle.pem" still fails. I have updated to the latest Docker image, and will update again next time the certificate is renewed.

**Comment by aptalca** [comment]
@Dalstroem the fix was merged on Dec 30th

**Comment by Dalstroem** [comment]
Hey @aptalca just a quick update. My certificate just renewed, and I can confirm that `priv-fullchain-bundle.pem` has the correct content with the current released Docker image `201, latest`.

Thanks for the support and fixing the issue! 😃
